ingress:
  - https://tiltakspenger-admin.dev.intern.nav.no
tenant: nav.no
ROLE_TPTS: 0405ed09-1248-47f7-a6e3-e998bc90feca
envs:
  - name: TILTAKSPENGER_VEDTAK_URL
    value: https://tiltakspenger-vedtak.dev.intern.nav.no
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/oauth2/v2.0/token
  - name: SCOPE
    value: eafda703-c821-44de-990c-950dec1ad22f