ingress:
  - https://tiltakspenger-admin.dev.intern.nav.no
replyURLs:
  - https://tiltakspenger-admin.dev.intern.nav.no/oauth2/callback
tenant: trygdeetaten.no
envs:
  - name: TILTAKSPENGER_VEDTAK_URL
    value: https://tiltakspenger-vedtak.dev.intern.nav.no