ingress:
  - https://tiltakspenger-admin.intern.nav.no
tenant: nav.no
ROLE_ADMIN: 0405ed09-1248-47f7-a6e3-e998bc90feca
envs:
  - name: TILTAKSPENGER_VEDTAK_URL
    value: http://tiltakspenger-vedtak
  - name: AUTH_PROVIDER_URL
    value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/oauth2/v2.0/token
  - name: SCOPE
    value: 9dd72d44-f3f7-48d1-846b-94f317d10119
